name: ciarama_api
description: API base para aplicativos da Ciarama
version: 1.5.0
author: Diego Lopes
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  url_launcher: ^5.1.2
  path_provider: ^1.1.0
  open_file: ^2.0.1+2
  timeago: ^2.0.18
  web_socket_channel: ^1.0.15
  intl: ^0.15.8
  pinput: ^0.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/
